:green_heart: Fix CI upgrade to libhal-cmake-util/3.0.0
libhal/libhal-armcortex pull request #152
Opened 2023-11-02 02:37 UTC by MaliaLabor

2023-11-02 19:34 UTC, kammce requested changes
What is this "setup.py" file?

2023-11-03 22:56 UTC, MaliaLabor commented
> What is this "setup.py" file?

No idea tbh, I deleted it

2023-11-05 12:11 UTC, kammce approved these changes

2023-11-05 13:20 UTC, kammce approved these changes

2023-11-05 13:20 UTC, merged